---
- hosts: localhost

  vars:
    nodeping_api_token: token-goes-here

  tasks:
    - name: Create PING check from localhost
      delegate_to: localhost
      nodeping:
        action: create
        checktype: PING
        target: example.com
        label: mytestcheck
        enabled: False
        token: "{{ nodeping_api_token }}"
        notifications:
        - group: your-group-id
          notifydelay: 2
          notifyschedule: All the time
        - contact: QEUVW
          notifydelay: 0
          notifyschedule: All the time
        - name: me
          address: me@example.com
          notifydelay: 0
          notifyschedule: All the time
      register: result
        
    - name: Output result of first creation
      debug:
        var: result

    - name: Get a check, run from localhost
      delegate_to: localhost
      nodeping:
        action: get
        checkid: "{{ result.message._id }}"
        token: "{{ nodeping_api_token }}"
      register: retrieved_check

    - name: Output result from GET
      debug:
        var: retrieved_check

    - name: Update the first check, run from target host
      nodeping:
        action: update
        token: "{{ nodeping_api_token }}"
        checkid: "{{ result['message']['_id'] }}"
        target: new.example.com
        label: thiswaschanged
        interval: 3
        threshold: 4
        notifications:
        - group: group-name-here
          notifydelay: 1
          notifyschedule: All the time
        - contact: QEUVW
          notifydelay: 0
          notifyschedule: Nights
        - name: me
          address: me@example.com
          notifydelay: 10
          notifyschedule: Weekdays
      register: check_updated

    - name: Output showing the check updates
      debug:
        var: check_updated

    - name: Delete the first check
      nodeping:
        action: delete
        token: "{{ nodeping_api_token }}"
        checkid: "{{ result['message']['_id'] }}"
      register: check_deleted

    - name: Output that the check was deleted
      debug:
        var: check_deleted
